version: '2'
services:
    reclameaqui-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        command: mongos --configdb reclameaqui-mongodb-config
    reclameaqui-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    reclameaqui-mongodb-config:
        image: mongo:3.6.3
        container_name: reclameaqui-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
